apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: web-port
      protocol: TCP
  selector:
      app: my-app
